db_file: "bot.db"

bot_url: "https://t.me/GB_task9_bot"

messages:
  response:
    start: "Привет! Чтобы сохранять ссылки в своём Pocket аккаунте, для начала необходимо дать мне доступ на это. Для этого переходи по ссылке:\n%s"
    already_authorized: "Вы уже проходили процесс авторизации. Можете присыдать ссылку для сохранения."
    unknown_command: "Данной команды нет в списке!"
    link_saved: "Ссылка успешно сохранена!"
  error:
    default: "Произошла ошибка!"
    invalid_url: "Невалидная ссылка!"
    unable_to_save: "Не удалось сохранить ссылку в Pocket. Повторите попытку!"